### ISSUE TITLE
Slow and understandable  robotic voice

### ISSUE THREAD

**Issue by miklax** [alexm8002/TeamSquawk-master#1]
Hello, 
when using on IVAO everyone can hear me 5/5, but I hear people very slow and understandable with robotic voice. It looks like there is some problem with buffering in my case or something like it. Maybe it would help if there is option to choose core audio or something like it is in TS3. Cheers.

**Comment by alexm8002** [comment]
Hi, I will need some more informations on your hardware to work this out.
For information, TS2 is not compatible with core audio, that's why TeamSquawk uses the Speex Codec.

**Comment by alexm8002** [comment]
Hi miklax,
You may want to try to use a different speed codec for your issue. Go to TeamSquawk preferences and sound. There you'll find a dropdown box with all speed codecs available

**Comment by gintoinc** [comment]
i've fixed the problem of robotic voice with headset changing configuration of midi sampling at 44.100

Application -> Utilities -> Midi setup -> Output headphones -> set from 48.000 to 41.000

Now it works
